<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
    <NuGetAuditLevel>critical</NuGetAuditLevel>
    <NuGetAudit>false</NuGetAudit>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DataArc.EntityFrameworkCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Database\DBModels\EmployeeAccessRequest.cs" />
    <Compile Remove="Database\DBModels\EmployeeOnboardingTask.cs" />
    <Compile Remove="Database\DBModels\EmployeePayrollRecord.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataArc.Orchestration.Framework.Demo.Application.Features\DataArc.Orchestration.Framework.Demo.Application.Features.csproj" />
  </ItemGroup>

</Project>