<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>9341d238-d287-4d3a-ad82-64209cafbf60</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Presentation\Demo.Host.Aspire.Web\Demo.Host.Aspire.Web.csproj" />
    <ProjectReference Include="..\..\..\Presentation\Demo.WebApi\Demo.WebApi.csproj" />
  </ItemGroup>

</Project>