<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
    <NuGetAuditLevel>critical</NuGetAuditLevel>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    <GenerateOpenApiDocuments>false</GenerateOpenApiDocuments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App\Demo.Application.Modules\Demo.Application.Modules.csproj" />
    <ProjectReference Include="..\..\Host\Demo.Host.Aspire\Demo.Host.Aspire.ServiceDefaults\Demo.Host.Aspire.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>