<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
    <NuGetAuditLevel>critical</NuGetAuditLevel>
    <NuGetAudit>false</NuGetAudit>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataArc.Orchestration.Framework.Demo.Application.Domain.SharedKernel\DataArc.Orchestration.Framework.Demo.Application.Domain.SharedKernel.csproj" />
  </ItemGroup>

</Project>
