<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
    <NuGetAuditLevel>critical</NuGetAuditLevel>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
    <GenerateOpenApiDocuments>false</GenerateOpenApiDocuments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataArc.Orchestration.Framework.Demo.Application.Modules\DataArc.Orchestration.Framework.Demo.Application.Modules.csproj" />
  </ItemGroup>

</Project>